# Generated by Django 4.1.4 on 2022-12-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='text',
        ),
        migrations.AddField(
            model_name='articles',
            name='image_url',
            field=models.CharField(default='url', max_length=200),
        ),
        migrations.AddField(
            model_name='articles',
            name='name',
            field=models.CharField(default='Article', max_length=200),
        ),
        migrations.AddField(
            model_name='articles',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
